import React from "react";
import { Grid, GridItem } from "@chakra-ui/react";
import UserHero from "~/components/UserHero";
import { api } from "~/utils/api";
import { getSession, useSession } from "next-auth/react";
import LeaderboardTable from "~/components/LeaderboardTable";
import Head from "next/head";

const Zone = () => {
  const { data: sessionData } = useSession();

  const {
    data: allPoints,
    refetch: refetchAllPoints,
    isLoading: isAllPointsLoading,
  } = api.points.getAll.useQuery(undefined, {
    enabled: sessionData?.user !== undefined,
  });

  const {
    data: pointsData,
    refetch: refetchPoints,
    isLoading: isPointsLoading,
  } = api.points.getLatest.useQuery(undefined, {
    enabled: sessionData?.user !== undefined,
  });

  const {
    data: statusData,
    refetch: refetchStatus,
    isLoading: isStatusLoading,
  } = api.status.getLatest.useQuery(undefined, {
    enabled: sessionData?.user !== undefined,
  });

  return (
    <>
      <Head>
        <title>EZ - Employee engagement Zone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        templateAreas={`"header header"
                  "nav main"
                  "nav footer"`}
        templateRows="repeat(12, 1fr)"
        templateColumns="repeat(5, 1fr)"
        h="100vh"
        gap="0"
        color="blackAlpha.700"
        fontWeight="bold"
        bg="#1A202C"
      >
        <GridItem pl="2" bg="#171923" rowSpan={1} colSpan={5}>
          Header
        </GridItem>
        <GridItem bg="#171923" rowSpan={12} colSpan={1} w="100%">
          <UserHero pointsData={pointsData} statusData={statusData} />
        </GridItem>
        <GridItem rowSpan={10} colSpan={4}>
          <Grid
            templateRows="repeat(2, 1fr)"
            templateColumns="repeat(2, 1fr)"
            gap={4}
            h="85vh"
            padding="4"
          >
            <GridItem
              w="100%"
              h="100%"
              bg="blue.500"
              rowSpan={1}
              colSpan={1}
              borderRadius="md"
            />
            <GridItem
              w="100%"
              h="100%"
              bg="#171923"
              rowSpan={1}
              colSpan={1}
              borderRadius="md"
            >
              <LeaderboardTable allPoints={allPoints} />
            </GridItem>
            <GridItem
              w="100%"
              h="100%"
              bg="blue.500"
              rowSpan={1}
              colSpan={1}
              borderRadius="md"
            />
            <GridItem
              w="100%"
              h="100%"
              bg="blue.500"
              rowSpan={1}
              colSpan={1}
              borderRadius="md"
            />
          </Grid>
        </GridItem>
        <GridItem pl="2" rowSpan={1} colSpan={1}>
          Footer
        </GridItem>
      </Grid>
    </>
  );
};

export default Zone;
