import React from "react";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";
import Sidebar from "../../components/Sidebar";

const Dashboard = () => {
  const { data: sessionData } = useSession();
  // trpc calls
  const { data: allStatus } = api.status.getAll.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <>
      <Head>
        <title>EZ - Employee engagement Zone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="relative flex h-screen w-screen items-center justify-center bg-slate-900">
        <div className="flex h-5/6 w-8/12 items-center justify-center">
          {/* here */}
          <Sidebar />
          <div className=" m-2 flex h-full w-9/12 items-center justify-center rounded bg-slate-800 p-12">
            <div className="h-full w-1/2">
              <div className="w-full">
                <p className="text-2xl">Status updates:</p>
                {allStatus?.map((status, index) => (
                  <div key={index} className="my-2 rounded bg-slate-700 p-2">
                    <p className="text-base text-red-500">{status.userName}</p>
                    <p className="py-2 text-sm">{status.status}</p>
                    <p className="text-sm text-slate-400">
                      {status.createdAt.toTimeString()}
                    </p>
                  </div>
                ))}
              </div>
              <div className="w-full">rewards</div>
            </div>
            <div className="h-full w-1/2">
              <div className="">leaderboard</div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Dashboard;
